apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: LoadBalancer
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkinsvolume
        persistentVolumeClaim:
          claimName: jenkinsvolume
      containers:
      - name: jenkins
        image: lolzah/jjajenkins:2
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
        volumeMounts:
        - name: jenkinsvolume
          mountPath: /var/jenkins_home
