apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkinsvolumespec
        persistentVolumeClaim:
          claimName: jenkinsvolume
      containers:
      - name: jenkins
        image: lolzah/jjajenkins:2
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkinsvolume
          mountPath: /var/jenkins_home
