apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: lolzah/jjajenkins:2
        ports:
        - containerPort: 8080
        - containerPort: 50000
      volumes:
      - name: jenkinsvolume
        persistentVolumeClaim:
          claimName: jenkinsvolume
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkinsvolume
