apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        -
          name: jenkinsvolume
          persistentVolumeClaim:
            claimName: jenkinsvolume
      containers:
        -
          name: jenkins
          image: 'lolzah/jjajenkins:2'
          ports:
            -
              containerPort: 8080
            -
              containerPort: 50000
          volumeMounts:
            -
              name: jenkinsvolume
              mountPath: /var/jenkins_home
          readinessProbe: null
           httpGet:
             port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins